name: GitHub-POC-Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        type: choice
        options:
          - DEV
          - UAT
          - PROD
      java:
        description: "Java Version"
        required: true
        type: choice
        options:
          - '8'
          - '17'
      commit:
        description: "Commit Message"
        required: true
        type: string

run-name: "GitHub-POC-Deployment | Environment: ${{ inputs.environment }} | ${{ inputs.commit }} | ${{ github.run_id }}"
          
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/${{ inputs.environment }}/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
    - name: Test with Maven
      run: mvn clean test
    - name: Upload MUnit reports
      uses: actions/upload-artifact@v4
      with:
        name: munit-test-reports
        path: target/site/munit/coverage

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/${{ inputs.environment }}/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
          
  deploy-cloudhub:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/${{ inputs.environment }}/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Download the JAR File
      uses: actions/download-artifact@v4
      with:
        name: artifacts
    - name: Deploy to ${{ inputs.environment }}
      env:
       grantType: ${{ secrets.grant_type }}
      run: |
        if [ "${{ inputs.environment }}" == "DEV" ];
        then
          mvn deploy -DskipTests -DmuleDeploy -DClientId="${{ secrets.dev_connected_app_id }}" -DClientSecret="${{ secrets.dev_connected_app_secret }}" -DGrantType="$grantType" -Denvironment="${{ inputs.environment }}" -D"application.name"="github-actions-poc-${{ inputs.environment }}"
        elif [ "${{ inputs.environment }}" == "UAT" ];
        then
          mvn deploy -DskipTests -DmuleDeploy -DClientId="${{ secrets.uat_connected_app_id }}" -DClientSecret="${{ secrets.uat_connected_app_secret }}" -DGrantType="$grantType" -Denvironment="${{ inputs.environment }}" -D"application.name"="github-actions-poc-${{ inputs.environment }}"
        else
          mvn deploy -DskipTests -DmuleDeploy -DClientId="${{ secrets.prod_connected_app_id }}" -DClientSecret="${{ secrets.prod_connected_app_secret }}" -DGrantType="$grantType" -Denvironment="${{ inputs.environment }}" -D"application.name"="github-actions-poc"
        fi
